##====== General parameters for the project ======###
general:
    ## To show prompt or not.
    verbose: True  ## True, False
    ## Project name. (A subfolder will be created for outputs.)
    project_name: 002_iPSC
    ## Main output folder.
    output_folder: C:/Repositories/Enrichment_analysis/analysis
    ## output_folder: D:/Repositories/Enrichment_analysis/analysis
    ## The full matrix file.
    input_whole_matrix: C:/Repositories/Enrichment_analysis/data/Matrix_All.txt
    ## input_whole_matrix: D:/Repositories/Enrichment_analysis/data/Matrix_All.txt
    ## The column name for significance.
    column_sig: Student's T-test Significant D336H_ipc
    ## The marking for significance.
    sig_mark: +
    ## The statistical significance matrix after functional enrichment analysis.
    input_sig_matrix: C:/Repositories/Enrichment_analysis/data/Matrix_404.txt
    ## input_sig_matrix: D:/Repositories/Enrichment_analysis/data/Matrix_404.txt
    ## Path to go.obo file.
    obo_file: C:/Repositories/Enrichment_analysis/data/go.obo
    ## obo_file: D:/Repositories/Enrichment_analysis/data/go.obo

##====== Gene ontology parameters ======###
go:
    ### (Optional) Filter the significance matrix.
    sig_matrix_filter:
        ## (Required) The column name of annotation category.
        column_category: Category column
        ## (Required) The target category(ies). (list-like)
        select_category:
            - GOBP
            - GOCC
            - GOMF
        ## The file name for saving the selected category matrix.
        save_to_file: df_GO_id.txt
    ### Annotate GO name, level, depth with GO id.
    ## Obsolete settings: https://github.com/tanghaibao/goatools/blob/main/notebooks/godag_obsolete_terms.ipynb
    ## Load obsolete GO terms or not.
    load_obsolete: False  # Default is "False".
    ## To remove the rows of obsolete GO terms.
    remove_obsolete: True
    ## The column containing GO id.
    column_id: Category value
    ## The new column for GO name.
    column_go_name: GO_name
    ## (Optional) Annotate level, depth to new column(s).
    column_go_level: GO_level
    column_go_depth: GO_depth
    ## Save the result matrix to file.
    save_go_file: True
    go_file_name: df_GO_name_drop.txt