##====== General parameters for the project ======###
general:
    # Project name. (A subfolder will be created for outputs.)
    project_name: 002_iPSC
    # Main output folder.
    output_folder: C:/Repositories/Enrichment_analysis/analysis
    # output_folder: D:/Repositories/Enrichment_analysis/analysis
    # Path to full matrix file.
    input_whole_matrix: C:/Repositories/Enrichment_analysis/data/Matrix_All.txt
    # input_whole_matrix: D:/Repositories/Enrichment_analysis/data/Matrix_All.txt
    # The column name for significance.
    column_sig: Student's T-test Significant D336H_ipc
    # The marking for significance.
    sig_mark: +
    # Path to statistical significance test result. (ex. Fisher's exact test)
    input_sig_matrix: C:/Repositories/Enrichment_analysis/data/Matrix_404.txt
    # input_sig_matrix: D:/Repositories/Enrichment_analysis/data/Matrix_404.txt
    # Path to go.obo file.
    obo_file: C:/Repositories/Enrichment_analysis/data/go.obo
    # obo_file: D:/Repositories/Enrichment_analysis/data/go.obo
    verbose: False  # True, False

##====== Gene ontology parameters ======###
go:
    # The column name of annotation category.
    column_category: Category column
    select_category:
        - GOBP
        - GOCC
        - GOMF
    # Save the selected category matrix to file.
    save_selected_file: False #True, False
    selected_file_name: df_GO_id.txt
    ### Annotate GO name, level, depth with GO id.
    ## Obsolete settings: https://github.com/tanghaibao/goatools/blob/main/notebooks/godag_obsolete_terms.ipynb
    # Load obsolete GO terms or not.
    load_obsolete: False  # Default is "False".
    # To remove the rows of obsolete GO terms.
    remove_obsolete: True
    # The column containing GO id.
    column_id: Category value
    # The new column for GO name.
    column_go_name: GO_name
    # (optional) Annotate level, depth to new column(s).
    column_go_level: GO_level
    column_go_depth: GO_depth
    # Save the result matrix to file.
    save_go_file: True
    go_file_name: df_GO_name_drop.txt